development: &development
  store_original_files: <%= ENV["PMP_STORE_ORIGINAL_FILES"] || true %>
  master_file_service_url: <%= ENV["PMP_MASTER_FILE_SERVICE_URL"] || "http://purl.dlib.indiana.edu/iudl/variations/master" %>
  access_file_service_url: <%= ENV["PMP_ACCESS_FILE_SERVICE_URL"] || "http://purl.dlib.indiana.edu/iudl/variations/access" %>
  purl_redirect_url: <%= ENV["PMP_PURL_REDIRECT_URL"] || "http://server1.variations2.indiana.edu/cgi-bin/access?%s" %>
  create_hocr_files: <%= ENV["PMP_CREATE_HOCR_FILES"] || true %>
  index_hocr_files: <%= ENV["PMP_INDEX_HOCR_FILES"] || true %>
  create_word_boundaries: <%= ENV["PMP_CREATE_WORD_BOUNDARIES"] || true %>
  allow_pdf_download: <%= ENV["PMP_ALLOW_PDF_DOWNLOAD"] || false %>

  fedora:
    user: fedoraAdmin
    password: fedoraAdmin
    url: http://localhost:8984/rest
    base_path: /dev
  solr:
    url: http://localhost:8983/solr/hydra-development
  db:
    adapter: sqlite3
    database: db/development.sqlite3
  redis:
    host: 127.0.0.1
    port: 6379
    namespace: catorax_dev
  rails:
    serve_static_files: true
    secret_key_base: 628b30efcdf28acbbd30a80e53e2b743d44f74bf393462badc49e0f5909ed109812ff12905e3a98bf4f81d3618fac5c061ad4e1ca5c91f9c1dce8226ca3cff25
  derivatives:
    path: <%= Rails.root.join("tmp/derivatives") %>
  ldap:
    enabled: false
    host: ads.iu.edu
    tree: dc=ads,dc=iu,dc=edu
    account_ou: ou=Accounts
    group_ou: ou=BL
    method: simple
    user: dlptech,ou=Accounts,dc=ads,dc=iu,dc=edu
    pass: changeme
    group_roles:
      admin:
        - CATORAX-USERS
test:
  fedora:
    user: fedoraAdmin
    password: fedoraAdmin
    url: http://localhost:<%= ENV['FCREPO_TEST_PORT'] || 8986 %>/rest
    base_path: /test
  solr:
    url: http://localhost:8985/solr/hydra-test
  db:
    adapter: sqlite3
    database: db/test.sqlite3
  redis:
    host: 127.0.0.1
    port: 6379
    namespace: catorax_test
  rails:
      serve_static_files: true
      secret_key_base: c9dd75fe2cce941807d14e04c09aa1f9ae41b6e1f7ba9d2f33142659acf9491f4a7835aad0c4110bf2fa40f2a1e6f7a62048b5a1e1a32c361c8c16d772e40bf0
  derivatives:
    path: <%= Rails.root.join("tmp/derivatives") %>
production: *development
